### PR TITLE
COMP: Add support for building against QT5 and VTK9

### PR DESCRIPTION
**Pull request by jamesfishbaugh**
Update to build with QT5 and VTK9 and drop support for previous versions of QT and VTK.

### CODE REVIEW

**Comment by jamesfishbaugh** [comment]
This should work cross platform but I was only able to test on linux. 

I visually compared between SlicerSALT 3.0 and this fix on a test dataset and found the results and functionality to be identical. 

However, 4/20 tests failed with the message `GLEW could not be initialized: Missing GL version`.

This may be related to driver issues on my machine: https://discourse.vtk.org/t/vtkwin32openglrenderwindow-glew-could-not-be-initialized-missing-gl-version/7517

**Comment by jcfr** [comment]
Nitpick: instead of merging master into the branch consider rebase.

**Comment by jcfr** [comment]
> However, 4/20 tests failed

All tests are now passing when the project is both built as standalone project or as a Slicer extension.

As fixed in 869b458d9 (BUG: Fix execution test instantiating vtkRenderWindow), tests should be using `vtkRenderWindow`.

```
Test project /home/jcfr/Projects/ShapePopulationViewer-build
      Start  1: TestShapePopulationBase_CreationSphereActor
 1/20 Test  #1: TestShapePopulationBase_CreationSphereActor ............   Passed    0.11 sec
      Start  2: TestShapePopulationBase_ChangeView
 2/20 Test  #2: TestShapePopulationBase_ChangeView .....................   Passed    0.29 sec
      Start  3: TestShapePopulationBase_setMeshOpacity
 3/20 Test  #3: TestShapePopulationBase_setMeshOpacity .................   Passed    0.16 sec
      Start  4: TestShapePopulationBase_setVectorScale
 4/20 Test  #4: TestShapePopulationBase_setVectorScale .................   Passed    0.16 sec
      Start  5: TestShapePopulationBase_computeCommonRange
 5/20 Test  #5: TestShapePopulationBase_computeCommonRange .............   Passed    0.14 sec
      Start  6: TestShapePopulationBase_UpdateColorMapByDirection
 6/20 Test  #6: TestShapePopulationBase_UpdateColorMapByDirection ......   Passed    0.20 sec
      Start  7: TestShapePopulationBase_setBackgroundSelectedColor
 7/20 Test  #7: TestShapePopulationBase_setBackgroundSelectedColor .....   Passed    0.28 sec
      Start  8: TestShapePopulationBase_setLabelColor
 8/20 Test  #8: TestShapePopulationBase_setLabelColor ..................   Passed    0.29 sec
      Start  9: TestShapePopulationBase_setBackgroundUnselectedColor
 9/20 Test  #9: TestShapePopulationBase_setBackgroundUnselectedColor ...   Passed    0.42 sec
      Start 10: TestShapePopulationBase_creationSphereWidget
10/20 Test #10: TestShapePopulationBase_creationSphereWidget ...........   Passed    0.17 sec
      Start 11: TestShapePopulationBase_displayColorbar
11/20 Test #11: TestShapePopulationBase_displayColorbar ................   Passed    0.16 sec
      Start 12: TestShapePopulationBase_displayAttribute
12/20 Test #12: TestShapePopulationBase_displayAttribute ...............   Passed    0.15 sec
      Start 13: TestShapePopulationBase_displayMeshName
13/20 Test #13: TestShapePopulationBase_displayMeshName ................   Passed    0.15 sec
      Start 14: TestShapePopulationBase_displayVectors
14/20 Test #14: TestShapePopulationBase_displayVectors .................   Passed    0.19 sec
      Start 15: TestShapePopulationBase_computeCommonAttributes
15/20 Test #15: TestShapePopulationBase_computeCommonAttributes ........   Passed    0.15 sec
      Start 16: TestShapePopulationBase_displayColorMap
16/20 Test #16: TestShapePopulationBase_displayColorMap ................   Passed    0.33 sec
      Start 17: TestShapePopulationBase_UpdateAttribute
17/20 Test #17: TestShapePopulationBase_UpdateAttribute ................   Passed    0.43 sec
      Start 18: TestShapePopulationBase_UpdateColorMapByMagnitude
18/20 Test #18: TestShapePopulationBase_UpdateColorMapByMagnitude ......   Passed    0.15 sec
      Start 19: TestShapePopulationBase_VectorsColorMode
19/20 Test #19: TestShapePopulationBase_VectorsColorMode ...............   Passed    0.61 sec
      Start 20: TestShapePopulationBase_getSelectedIndex
20/20 Test #20: TestShapePopulationBase_getSelectedIndex ...............   Passed    0.19 sec
```

**Comment by jcfr** [comment]
Closing. This is pull request is superseded by https://github.com/NIRALUser/ShapePopulationViewer/pull/61

The pull request was based of the branch `slicersalt-2022-01-11-22ca6bf` associated with SlicerSALT which was originally based of a very old `ShapePopulationViewer` version (based of `slicersalt/ShapePopulationViewer@master` from December 2018)

The branch `slicersalt-2022-01-11-22ca6bf` will also be deleted

**Pull request closed without merging**
