### PR TITLE
Color by direction

### PR DESCRIPTION
**Pull request by laurapascal**
Creation of two color maps to visualize the direction of the vectors in a model: 
- a first one which displays the same color for one direction and the opposite direction
- a second one which displays one direction and its opposite with different colors

Correction some bugs from the previous version of Shape Population Viewer: 
- RAS View
- Adding a title to the scalar bar in order to avoid an error with the VTK 6 and above.
- Allow the user to display vectors only when a 3D Attribute is selected and only on the selected meshes

### CODE REVIEW

**Comment by agirault** [comment]
Thank you for your work @laurapascal !

Could you give an overall description of your work in the PR conversation (if this is ok @fbudin69500)? It is also a good exercise for getting used to creating merge-requests.

I would like to know if this will be compatible as a Slicer extension. If yes, could we look into updating it [1] ? Also please feel free to add yourself as a contributor on the wiki page and as the current contact.

[1] http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Extensions/ShapePopulationViewer

I just wanted to leave a word for the Slicer side, I believe @fbudin69500 will be the one to review and merge. If need be I'd be happy to test.

**Comment by fbudin69500** [comment]
@laurapascal : As Alexis said, could you add a description to this pull request. It should be fairly easy as what you added is a failry self-contained new feature (plus a few bug corrections). Ideally, you would want to re-write your history in your branch to split what is the new feature and what is bug corrections. This would allow you to do a pull-request for the new feature itself, and then different pull-requests for each bug correction (that are not part of your new feature). Also, as Alexis mentioned, please update the Slicer wiki [1] to add your name as a contributor (and add some explanations and screenshots of your new feature), and update the CMakeLists.txt also for the same reasons.
@agirault : Thanks for the review! The Slicer extension will be updated. The extension index will be updated as soon as the new version of the extension seems to work.

[1] http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Extensions/ShapePopulationViewer

**Comment by agirault** [comment]
Thank you! :+1: 

@laurapascal maybe you can also add the explanations for your changes on NITRC [1] and update the packages? 

[1] http://www.nitrc.org/projects/shapepopviewer

**Comment by fbudin69500** [comment]
@laurapascal : Can you update the documentation that is available on NITRC? (there is an odp file) If you do not have an account on NITRC yet, please create one, and I will add you to the project. As for the package, we will see if we update it or not later, it is not the most urgent thing to do.

**Pull request merged**
